### ISSUE TITLE
Stop elastic search before server install

### ISSUE THREAD

**Issue by bkreider** [ContinuumIO/runbooks#41]
Stop elastic search before server install.

If you don't, it sometimes leads to ES errors that take about 5 commands to fix.

**Comment by damianavila** [comment]
I am interested in the five command to fix it, can you share that info @bkreider, I think it would be useful to save it somewhere...

**Comment by bkreider** [comment]
@damianavila 
```
sudo service wakari-server stop
sudo service elasticsearch stop
sudo rm -rf /var/lib/elasticsearch/*
sudo service elasticsearch start
sudo service wakari-server start
```

**Comment by damianavila** [comment]
Thanks for the reference, I think it was also referenced in FD but it is nice to have it here as well. Thanks!

**Comment by bkreider** [comment]
Np.  I have a messy page here for my personal knowledgebase:  https://sites.google.com/a/continuum.io/wiki/sales/implementation-engineering/knowldege-base?pli=1

**Comment by damianavila** [comment]
Thanks!
