### ISSUE TITLE
assembling sets of smaller tarballs

### ISSUE THREAD

**Issue by bkreider** [ContinuumIO/runbooks#64]
how do we do this?

**Comment by amccarty** [comment]
Related to https://github.com/ContinuumIO/implementation_engineering/issues/32

**Comment by amccarty** [comment]
@bkreider Check section 2.7.11 here: https://github.com/ContinuumIO/runbooks/blob/reassembly/AnacondaRepo.rst
Let me know what you think...

**Comment by mrduane** [comment]
@amccarty @bkreider 

> The installer does not contain packages for Anaconda Notebook, Anaconda Cluster or R for 64-Bit Linux. The full TAR archive is required if these packages are needed.

I don't think this is what we want. My understanding was that the each platform archive would still contain the R packages. They'd just be broken out to a separate directory, so they could be mirrored to their own channel. Let me know if that doesn't make sense.

**Comment by amccarty** [comment]
Right now only the [linux 64 tarball](https://s3.amazonaws.com/continuum-airgap/2016-08/linux-64-2016-08-03.tar) is configured like this. If someone wants R for linux 64, they grab [this tarball](https://s3.amazonaws.com/continuum-airgap/2016-08/linux-64-R-Packages-2016-08-03.tar). I did this to keep the linux 64 tarball as lean as I could. Other platform tarballs (currently) have R included. Should we create separate R tarballs for each platform? R adds at most 3GB to the tarball size, so at worst folks get 3GB of "extras", and arguably more than that before they even install R. If we include R in each tarball but in a separate directory, we'll need to incorporate that into the docs.

**Comment by amccarty** [comment]
Talked to @mrduane  - we're going to go with a single R-tarball for all platforms, keeping R out of the platform-based tarballs. @trentoliphant @bkreider please re-open if you strongly disagree.
