### ISSUE TITLE
What does  `Configure Anaconda Client` in final section do?

### ISSUE THREAD

**Issue by sandhujasmine** [ContinuumIO/runbooks#67]
In the [final section](http://runbooks.readthedocs.io/en/latest/AnacondaEnterpriseNotebooks.html#configure-anaconda-client). Does the following write to a config file?

`anaconda config --set url http://<your Anaconda Server>:8080/api -s`

I don't see any changes in .condarc on the AEN compute node. Just curious how this values is set globally - some config file, I assume but which one?

**Comment by mrduane** [comment]
@sandhujasmine sorry, just seeing this. @bkreider has dealt with this, and can answer.

**Comment by bkreider** [comment]
This sets up the global config file for anaconda-client.  It's in some weird place like /etc/xvdg or something like that.
