### ISSUE TITLE
Add test of cloning default env

### ISSUE THREAD

**Issue by bkreider** [ContinuumIO/runbooks#85]
Add this to the runbooks (from the update instructions):

```
sudo -u wakari /opt/wakari/anaconda/bin/conda create -p /opt/wakari/testenv --clone root
rm -rf /opt/wakari/testenv
```

This will make sure that the .condarc is correct and that it can clone the default environment.

**Comment by sandhujasmine** [comment]
Added in [this commit](https://github.com/ContinuumIO/runbooks/commit/d14695a72a335cb063ea534575a7e6eaca2e592f)
